# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-frontend

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ui

    strategy:
      matrix:
        node-version: [16, 18]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: start notification
        id: slack_start
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "*[http-chat-ui]* Start: Frontend CI"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./ui/package-lock.json
      - run: npm ci
      - run: npm run build
        env:
          REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          REACT_APP_BACKEND_BASEURL: ${{ secrets.BACKEND_BASEURL }}
      - name: complete notification
        id: slack_complete
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "*[http-chat-ui]* Completed: Frontend CI"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
